FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG FIREBASE_CREDENTIALS
ARG FIREBASE_WEB_API_KEY
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET

# Compila la aplicación
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o main .

# Imagen final ligera (sin herramientas de compilación)
FROM alpine:3.21

WORKDIR /app

COPY --from=builder /app/main .

ENV FIREBASE_CREDENTIALS=$FIREBASE_CREDENTIALS
ENV FIREBASE_WEB_API_KEY=$FIREBASE_WEB_API_KEY
ENV CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
ENV CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET

EXPOSE 8080

CMD ["./main"]