name: CD action

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed] # (mergeado)
    branches: [main]

jobs:
  deploy:
    if: github.event.pull_request.merged == true # Solo si se hizo merge
    name: CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 👉 Build Docker image
      - name: Build Docker image
        run: |
          set -x
          docker build \
            --build-arg FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }} \
            --build-arg FIREBASE_WEB_API_KEY=${{ secrets.FIREBASE_WEB_API_KEY }} \
            --build-arg CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
            --build-arg CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
            --build-arg CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
            -f Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/talkus-backend-${{ github.event.number }}:${{ github.sha }} \
            .

      # 👉 Log in to DockerHub
      - name: DockerHub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 👉 Push the Docker image
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/talkus-backend-${{ github.event.number }}:${{ github.sha }}

      # 👉 Login into tailscale
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      # 👉 Pull and build Docker image
      - name: SSH to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd documents/dockers-projects/talkus/
            sed -i '/^DOCKER_IMAGE_BACKEND_DEV=/d' .env.backend
            echo "DOCKER_IMAGE_BACKEND_DEV=${{ secrets.DOCKER_USERNAME }}/talkus-backend-${{ github.event.number }}:${{ github.sha }}" >> .env
            docker compose up -d backend-dev
